[book]
authors = ["rxdn", "Ticketsbot-cloud"]
language = "en"
multilingual = false
src = "src"
title = "Tickets V2 Docs"
description = "Official Documentation of the Tickets V2 Discord Bot"

[output.html]
default-theme = "ayu"
